apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: todo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: gp2   # Uncomment for AWS EKS (gp2 or gp3)
  # storageClassName: standard  # Default for Minikube (already set automatically)
